/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnthologyRouteImport } from './routes/anthology'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as MeRouteImport } from './routes/me'
import { Route as SeekRouteImport } from './routes/seek'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnthologyRoute = AnthologyRouteImport.update({
  id: '/anthology',
  path: '/anthology',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekRoute = SeekRouteImport.update({
  id: '/seek',
  path: '/seek',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anthology': typeof AnthologyRoute
  '/compose': typeof ComposeRoute
  '/me': typeof MeRoute
  '/seek': typeof SeekRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anthology': typeof AnthologyRoute
  '/compose': typeof ComposeRoute
  '/me': typeof MeRoute
  '/seek': typeof SeekRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anthology': typeof AnthologyRoute
  '/compose': typeof ComposeRoute
  '/me': typeof MeRoute
  '/seek': typeof SeekRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/anthology' | '/compose' | '/me' | '/seek' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/anthology' | '/compose' | '/me' | '/seek' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anthology'
    | '/compose'
    | '/me'
    | '/seek'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnthologyRoute: typeof AnthologyRoute
  ComposeRoute: typeof ComposeRoute
  MeRoute: typeof MeRoute
  SeekRoute: typeof SeekRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anthology': {
      id: '/anthology'
      path: '/anthology'
      fullPath: '/anthology'
      preLoaderRoute: typeof AnthologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seek': {
      id: '/seek'
      path: '/seek'
      fullPath: '/seek'
      preLoaderRoute: typeof SeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnthologyRoute: AnthologyRoute,
  ComposeRoute: ComposeRoute,
  MeRoute: MeRoute,
  SeekRoute: SeekRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
